# Generated by Django 4.2.5 on 2023-10-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_image'),
        ('lesson', '0002_alter_lesson_options_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Название курса'),
        ),
    ]
